In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.25, random_state = 0)

In [8]:
#Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
# GridSearchCV model training
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features': ['sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
# Best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}
The best score is:  0.7101216816812587

In [11]:
# Gridsearchcv results
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010527,0.001194,0.004785,0.001585,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.704336,0.612717,0.750049,0.681658,0.726505,0.695053,0.047029,6
1,0.007031,0.002296,0.004075,0.000605,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.586586,0.493354,0.672035,0.690092,0.497637,0.587941,0.083199,16
2,0.008908,0.001974,0.004512,0.001284,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.751921,0.591366,0.676238,0.693329,0.743409,0.691253,0.057633,7
3,0.009529,0.002767,0.005358,0.000748,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.604070,0.506651,0.629420,0.682099,0.713769,0.627202,0.071526,15
4,0.008926,0.000913,0.004289,0.000501,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.790491,0.598802,0.739682,0.625117,0.796517,0.710122,0.082964,1
5,0.005851,0.000936,0.004909,0.001259,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.588836,0.564863,0.633988,0.677119,0.719328,0.636827,0.056427,14
6,0.007935,0.001066,0.004893,0.000864,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.716545,0.635436,0.709881,0.733096,0.742798,0.707551,0.037899,3
7,0.007268,0.001949,0.004220,0.000767,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.674727,0.647060,0.622169,0.685804,0.659244,0.657801,0.022171,11
8,0.039637,0.011869,0.003689,0.000397,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.695335,0.663426,0.730173,0.668929,0.739090,0.699391,0.030859,4
9,0.034409,0.024122,0.005364,0.001718,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.723447,0.548705,0.561076,0.766942,0.662862,0.652606,0.086452,12
10,0.027185,0.008845,0.005431,0.002339,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.748233,0.629237,0.610667,0.702012,0.643736,0.666777,0.050922,9
11,0.019239,0.003274,0.003934,0.001028,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.681345,0.660291,0.604406,0.641886,0.701948,0.657975,0.033507,10
12,0.013954,0.007173,0.011735,0.009310,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.772976,0.596541,0.776811,0.678504,0.715728,0.708112,0.066797,2
13,0.009593,0.006064,0.003178,0.000690,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.666613,0.552059,0.716056,0.706665,0.698006,0.667880,0.060248,8
14,0.009024,0.002602,0.004816,0.001172,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.746383,0.655856,0.620612,0.705112,0.760311,0.697655,0.052988,5
15,0.006409,0.000938,0.003650,0.000841,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.620721,0.642041,0.658597,0.630926,0.655177,0.641492,0.014305,13

In [12]:
# user inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [13]:
# Model Prediction
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [2597.779]

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(