In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# GridSearchCV model training
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features': ['sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
# Best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'}
The best score is:  0.6957384264274458

In [9]:
# Gridsearchcv results
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016864,0.008646,0.008064,0.005201,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.704208,0.619582,0.688659,0.742926,0.723317,0.695738,0.042211,1
1,0.006543,0.001742,0.004229,0.001388,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.642537,0.489562,0.702254,0.525200,0.696505,0.611212,0.088025,15
2,0.009413,0.002728,0.005864,0.002314,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.713348,0.605950,0.724322,0.697258,0.692524,0.686681,0.041932,3
3,0.005668,0.000451,0.004497,0.001417,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.681294,0.555424,0.708919,0.666580,0.616326,0.645709,0.054244,10
4,0.007571,0.001425,0.004396,0.001246,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.743037,0.615938,0.674500,0.730470,0.703049,0.693399,0.045362,2
5,0.005655,0.000909,0.004160,0.001674,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.584066,0.469062,0.585402,0.630484,0.508024,0.555407,0.058409,16
6,0.007065,0.001902,0.003525,0.001211,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.663879,0.601276,0.700160,0.711101,0.727123,0.680708,0.044831,4
7,0.007015,0.001243,0.003065,0.000305,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.700397,0.389743,0.724849,0.678170,0.754573,0.649546,0.132366,9
8,0.024003,0.002228,0.003946,0.001067,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.554176,0.494492,0.697265,0.618904,0.724580,0.617884,0.085989,14
9,0.017526,0.002909,0.002619,0.000275,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.664707,0.514248,0.689572,0.726658,0.738319,0.666701,0.080614,7
10,0.025814,0.006847,0.003024,0.000769,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.685411,0.584880,0.541005,0.670826,0.660935,0.628611,0.055929,13
11,0.019312,0.004618,0.003239,0.000921,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.761774,0.529616,0.716564,0.682101,0.627056,0.663422,0.080091,8
12,0.010535,0.004851,0.006143,0.004251,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.676004,0.598553,0.718463,0.682108,0.674309,0.669888,0.039127,5
13,0.006690,0.001915,0.003782,0.000858,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.655002,0.511300,0.668986,0.688382,0.676016,0.639937,0.065218,11
14,0.008438,0.001683,0.004133,0.000647,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.663038,0.513635,0.636279,0.604895,0.760806,0.635730,0.080309,12
15,0.007192,0.001470,0.003992,0.000748,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.658487,0.603466,0.734384,0.701365,0.650846,0.669710,0.044844,6

In [10]:
# user inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [11]:
# Model Prediction
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [2639.0429]

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(