In [1]:
# Importing necssary libraries
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Training and testing data
X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [8]:
#Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Model training GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [11]:
# Best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}
The best score is:  0.8138629653898992

In [12]:
# GridsearchCV results
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.069388,0.019816,0.013976,0.007917,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.848057,0.780136,0.793560,0.793291,0.717394,0.786487,0.041717,12
1,0.519384,0.189455,0.021307,0.002618,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.867423,0.786685,0.810406,0.831909,0.770220,0.813328,0.034200,3
2,0.070112,0.023478,0.006294,0.002451,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.851812,0.761020,0.792328,0.806382,0.768697,0.796048,0.032265,10
3,0.402872,0.067544,0.025788,0.010411,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.863822,0.790929,0.804964,0.830223,0.770264,0.812040,0.032413,5
4,0.089346,0.003828,0.003869,0.000116,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.855831,0.773071,0.809510,0.801483,0.770880,0.802155,0.030853,9
5,0.837744,0.050516,0.021186,0.003570,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.861341,0.795888,0.807213,0.826854,0.775379,0.813335,0.029223,2
6,0.085824,0.006233,0.003591,0.000282,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.851232,0.778369,0.757784,0.773333,0.741585,0.780461,0.037654,15
7,1.187913,0.268067,0.038622,0.006627,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855042,0.794824,0.816678,0.821764,0.772221,0.812106,0.027739,4
8,0.046406,0.003949,0.005192,0.000510,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.816798,0.787288,0.739645,0.805098,0.752949,0.780356,0.029654,16
9,0.563693,0.014541,0.042314,0.006312,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.862647,0.791804,0.811088,0.832425,0.771350,0.813863,0.031705,1
10,0.086394,0.013513,0.010873,0.003856,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.814558,0.785310,0.782266,0.777578,0.746616,0.781266,0.021633,14
11,0.829089,0.086044,0.065757,0.012916,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.865058,0.788555,0.807070,0.823766,0.766880,0.810266,0.033312,7
12,0.074427,0.003376,0.008130,0.000850,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.830297,0.772868,0.780217,0.798908,0.759352,0.788329,0.024567,11
13,0.796663,0.067471,0.043823,0.012943,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859276,0.793366,0.809997,0.830855,0.764936,0.811686,0.032113,6
14,0.086748,0.006622,0.007992,0.000417,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.805827,0.764790,0.796653,0.817440,0.730200,0.782982,0.031664,13
15,0.801911,0.071815,0.035593,0.008586,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861173,0.790820,0.807390,0.824961,0.766735,0.810216,0.031902,8

In [13]:
# Usrr inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [14]:
# Model predictions
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [15515.0766471]