In [1]:
# Importing necssary libraries
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [7]:
# Training and testing data
#X_train,X_test,Y_train,Y_test = train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [ ]:
# Model training GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [ ]:
# Best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'criterion': 'poisson', 'max_features': 'log2', 'n_estimators': 100}
The best score is:  0.8344421803519154

In [ ]:
# GridsearchCV results
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.096636,0.014938,0.014864,0.003866,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.848993,0.759469,0.842577,0.813246,0.822353,0.817328,0.031717,13
1,0.797659,0.030787,0.049391,0.004370,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.853981,0.773046,0.863994,0.825717,0.839635,0.831274,0.031867,7
2,0.083115,0.005652,0.013322,0.002286,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.839062,0.769098,0.840199,0.819950,0.825905,0.818843,0.026040,10
3,0.767248,0.036831,0.046837,0.003498,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.861599,0.776003,0.858745,0.830121,0.841675,0.833629,0.031019,3
4,0.278545,0.033024,0.013041,0.002747,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.843742,0.766784,0.838452,0.826658,0.826566,0.820440,0.027650,9
5,2.762651,0.199315,0.045554,0.008644,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856926,0.783969,0.853053,0.827870,0.842121,0.832788,0.026412,4
6,0.279763,0.037574,0.015300,0.005692,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.820121,0.775322,0.829229,0.812124,0.827470,0.812853,0.019717,15
7,2.710748,0.260060,0.047720,0.001909,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.852773,0.781603,0.855253,0.825637,0.838899,0.830833,0.026808,8
8,0.079135,0.004237,0.011376,0.002454,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.847263,0.757617,0.841408,0.812167,0.832897,0.818270,0.032576,11
9,0.797443,0.075797,0.049871,0.005510,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.858269,0.781036,0.865704,0.826676,0.836719,0.833681,0.029866,2
10,0.083271,0.014818,0.011138,0.002199,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.841781,0.753090,0.839551,0.814917,0.813546,0.812577,0.032017,16
11,0.837115,0.109489,0.049170,0.003327,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.854476,0.778435,0.861418,0.826193,0.837214,0.831547,0.029325,6
12,0.114799,0.025459,0.014893,0.002377,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.846456,0.749456,0.838214,0.816370,0.840205,0.818140,0.035811,12
13,0.954194,0.091321,0.048634,0.004953,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858173,0.779653,0.863860,0.821398,0.837783,0.832173,0.030285,5
14,0.115597,0.021525,0.014817,0.007446,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.834640,0.755760,0.850658,0.806022,0.828764,0.815169,0.032974,14
15,0.957331,0.039985,0.049862,0.006580,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857077,0.781220,0.862358,0.830245,0.841311,0.834442,0.028945,1

In [ ]:
# Usrr inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [ ]:
# Model predictions
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [4228.6217257]

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(