In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [18]:
#Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['linear','poly','rbf'], 'C':[1,10,100,1000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(),param_grid,verbose=3,refit=True,n_jobs=-1)
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [1, 10, 100, 1000], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'poly', 'rbf']},
             verbose=3)

In [ ]:
# Displaying the best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}
The best score is:  0.7935546451669505

In [ ]:
# results of gridsearchcv
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.027496,0.003137,0.005072,0.000516,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",0.016409,0.033832,-0.083831,-0.078347,-0.084332,-0.039254,0.052891,17
1,0.029445,0.005133,0.005629,0.001040,1,auto,poly,"{'C': 1, 'gamma': 'auto', 'kernel': 'poly'}",-0.031767,-0.027414,-0.136684,-0.126981,-0.132021,-0.090973,0.050232,22
2,0.051972,0.030128,0.021213,0.005054,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",-0.037151,-0.032999,-0.143607,-0.134309,-0.137861,-0.097185,0.050817,23
3,0.032243,0.010980,0.005388,0.001716,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",0.016409,0.033832,-0.083831,-0.078347,-0.084332,-0.039254,0.052891,17
4,0.030538,0.010020,0.004685,0.000172,1,scale,poly,"{'C': 1, 'gamma': 'scale', 'kernel': 'poly'}",-0.031902,-0.027215,-0.136794,-0.126911,-0.132027,-0.090970,0.050261,21
5,0.044807,0.017374,0.017918,0.001966,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",-0.037143,-0.033009,-0.143600,-0.134313,-0.137861,-0.097185,0.050815,24
6,0.028799,0.006259,0.006010,0.002616,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,11
7,0.043545,0.023197,0.005065,0.001030,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,16
8,0.040277,0.012881,0.017553,0.001400,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,19
9,0.025340,0.001403,0.004677,0.000596,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,11
10,0.033413,0.011114,0.004721,0.000163,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,15
11,0.040737,0.011488,0.023054,0.004544,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,20
12,0.038070,0.013055,0.007629,0.003914,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,7
13,0.028356,0.001565,0.004963,0.000367,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,9
14,0.040796,0.011315,0.024143,0.005383,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,13
15,0.033935,0.006011,0.004392,0.000336,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,7
16,0.044190,0.021751,0.004899,0.000689,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,10
17,0.031202,0.001453,0.017151,0.000523,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,14
18,0.039168,0.000677,0.004328,0.000199,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,5
19,0.048791,0.010476,0.004966,0.000484,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,1
20,0.045982,0.005908,0.019647,0.003393,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,4
21,0.042822,0.005828,0.004396,0.000280,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,5
22,0.052035,0.017049,0.004415,0.000754,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,2
23,0.039754,0.000835,0.016893,0.000615,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,3

In [ ]:
# User inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [ ]:
# Model prediction
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [674600.23518583]