In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.25, random_state = 0)

In [9]:
#Data standardization
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['linear','poly','rbf'], 'C':[1,10,100,1000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(),param_grid,verbose=3,refit=True,n_jobs=-1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [1, 10, 100, 1000], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'poly', 'rbf']},
             verbose=3)

In [12]:
# Displaying the best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}
The best score is:  0.79703027915612

In [13]:
# results of gridsearchcv
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.041679,0.008323,0.007559,0.001914,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",-0.014452,0.062935,-0.066222,-0.102854,-0.070362,-0.038191,0.057952,17
1,0.036033,0.003455,0.006477,0.001130,1,auto,poly,"{'C': 1, 'gamma': 'auto', 'kernel': 'poly'}",-0.062133,-0.005123,-0.123808,-0.163666,-0.125800,-0.096106,0.055939,22
2,0.040917,0.003122,0.021541,0.001648,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",-0.067485,-0.011208,-0.133039,-0.171949,-0.132021,-0.103140,0.056896,24
3,0.029898,0.005621,0.006431,0.001688,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",-0.014452,0.062935,-0.066222,-0.102854,-0.070362,-0.038191,0.057952,17
4,0.035958,0.007566,0.005870,0.001646,1,scale,poly,"{'C': 1, 'gamma': 'scale', 'kernel': 'poly'}",-0.062048,-0.005282,-0.123826,-0.163623,-0.125739,-0.096104,0.055882,21
5,0.045442,0.014115,0.026822,0.010535,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",-0.067490,-0.011199,-0.133038,-0.171951,-0.132024,-0.103140,0.056898,23
6,0.037808,0.014812,0.004978,0.000601,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.361367,0.521958,0.361271,0.343372,0.359436,0.389481,0.066581,11
7,0.035237,0.007823,0.005980,0.001159,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.026240,0.100046,-0.025049,-0.050695,-0.032161,0.003676,0.054520,16
8,0.058254,0.015996,0.028536,0.007580,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.024879,0.041060,-0.089414,-0.126034,-0.088917,-0.057637,0.059128,19
9,0.030433,0.003746,0.005178,0.001355,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.361367,0.521958,0.361271,0.343372,0.359436,0.389481,0.066581,11
10,0.033501,0.004944,0.010774,0.007148,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.027066,0.098580,-0.025212,-0.050252,-0.031590,0.003719,0.053926,15
11,0.041008,0.006115,0.020115,0.002101,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.024922,0.041149,-0.089405,-0.126060,-0.088950,-0.057637,0.059161,20
12,0.051638,0.009416,0.005953,0.001599,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.569478,0.663539,0.584270,0.563851,0.566393,0.589506,0.037688,7
13,0.037735,0.008424,0.009062,0.008330,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.522332,0.603337,0.525688,0.527354,0.463853,0.528513,0.044333,10
14,0.036431,0.002222,0.021020,0.002513,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.281150,0.394108,0.211328,0.206719,0.216700,0.262001,0.071407,13
15,0.050058,0.009922,0.007183,0.001478,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.569478,0.663539,0.584270,0.563851,0.566393,0.589506,0.037688,7
16,0.044771,0.012157,0.005351,0.000683,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.524638,0.600114,0.525333,0.528394,0.465482,0.528792,0.042719,9
17,0.038793,0.007298,0.020006,0.001223,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.280865,0.394626,0.211386,0.206566,0.216436,0.261976,0.071633,14
18,0.047661,0.004535,0.005183,0.001081,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.585184,0.563261,0.693222,0.568481,0.650110,0.612052,0.051065,5
19,0.056368,0.007692,0.005944,0.000873,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.828209,0.794088,0.801112,0.810819,0.750462,0.796938,0.025908,2
20,0.056212,0.012338,0.025172,0.006946,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.749498,0.760005,0.731071,0.737441,0.687571,0.733117,0.024854,3
21,0.046211,0.003096,0.005705,0.001366,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.585184,0.563261,0.693222,0.568481,0.650110,0.612052,0.051065,5
22,0.066305,0.018280,0.005356,0.001770,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828742,0.793712,0.801005,0.810846,0.750846,0.797030,0.025909,1
23,0.047655,0.012542,0.019597,0.005274,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.749352,0.760205,0.731117,0.737347,0.687443,0.733093,0.024921,4

In [14]:
# User inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [15]:
# Model prediction
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [2517040.6525348]