In [1]:
# Importing necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [8]:
# GridSearchCV model training
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],'max_features': ['sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
# Best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'random'}
The best score is:  0.7030569434835392

In [10]:
# Gridsearchcv results
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.020604,0.004385,0.008077,0.000601,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.652822,0.546993,0.634998,0.632738,0.723840,0.638278,0.056404,14
1,0.011833,0.002841,0.007526,0.001586,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.706893,0.628497,0.557910,0.662759,0.685320,0.648276,0.052106,12
2,0.015111,0.002109,0.007160,0.000640,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.747485,0.590284,0.712941,0.695917,0.710246,0.691375,0.053310,4
3,0.010526,0.000981,0.007035,0.001419,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.714835,0.526728,0.736405,0.702293,0.616621,0.659376,0.077813,10
4,0.011805,0.000762,0.005831,0.000358,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.707759,0.608576,0.695638,0.682125,0.729523,0.684724,0.041139,5
5,0.012173,0.000778,0.007310,0.001090,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.676875,0.553370,0.671298,0.678794,0.653244,0.646716,0.047537,13
6,0.015913,0.005081,0.007064,0.001187,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.753727,0.575024,0.723673,0.735752,0.726542,0.702944,0.064816,2
7,0.011582,0.002998,0.006765,0.001224,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.640853,0.489618,0.675333,0.633929,0.628278,0.613602,0.064116,15
8,0.053123,0.008762,0.007267,0.001508,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.746707,0.545257,0.736979,0.607118,0.755212,0.678255,0.085797,7
9,0.038786,0.004996,0.006251,0.000829,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.776675,0.558624,0.753523,0.699916,0.631311,0.684010,0.080213,6
10,0.057833,0.006712,0.005881,0.000250,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.704604,0.562533,0.684368,0.647939,0.748730,0.669635,0.062670,9
11,0.040403,0.007036,0.008938,0.003840,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.722241,0.613463,0.732258,0.737717,0.709605,0.703057,0.045808,1
12,0.013963,0.001428,0.007116,0.000939,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.765135,0.614218,0.739576,0.627542,0.724605,0.694215,0.061410,3
13,0.013089,0.002346,0.007908,0.001974,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.717044,0.558771,0.496511,0.648694,0.636220,0.611448,0.076337,16
14,0.013900,0.001075,0.005926,0.000943,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.679969,0.633483,0.710468,0.693456,0.650636,0.673602,0.028038,8
15,0.015888,0.007389,0.006533,0.000474,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.655827,0.554375,0.668845,0.736749,0.626019,0.648363,0.059364,11

In [11]:
# user inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [12]:
# Model Prediction
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [3077.0955]

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(