In [1]:
# Importing necssary libraries
import pandas as pd

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [8]:
# Model training GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],'max_features': ['sqrt','log2'],'n_estimators':[10,100]}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [9]:
# Best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}
The best score is:  0.8342703781364905

In [10]:
# GridsearchCV results
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.054036,0.002184,0.008108,0.000999,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.830488,0.762308,0.843481,0.803540,0.827137,0.813391,0.028612,16
1,0.630218,0.120266,0.048024,0.007943,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.854780,0.782426,0.861888,0.826678,0.841148,0.833384,0.028186,5
2,0.059821,0.008690,0.013538,0.010292,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.842666,0.752534,0.850143,0.827209,0.834028,0.821316,0.035254,9
3,0.735957,0.059528,0.048655,0.003400,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.855670,0.776132,0.862462,0.833125,0.842061,0.833890,0.030640,4
4,0.299787,0.019839,0.019384,0.006753,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.848426,0.764965,0.832188,0.812321,0.831624,0.817905,0.028836,13
5,2.962623,0.146523,0.057090,0.007624,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856885,0.782475,0.859701,0.830701,0.840519,0.834056,0.027901,2
6,0.287134,0.017520,0.011731,0.002044,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.832419,0.759760,0.831558,0.821523,0.848394,0.818731,0.030716,11
7,2.851415,0.107907,0.044543,0.003650,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.857603,0.782108,0.859810,0.827141,0.842801,0.833892,0.028427,3
8,0.094787,0.001892,0.014337,0.002408,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.838340,0.759962,0.837671,0.826840,0.831713,0.818905,0.029770,10
9,0.814962,0.026883,0.050223,0.002023,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856229,0.781226,0.863539,0.828298,0.842060,0.834270,0.029151,1
10,0.091944,0.006986,0.013740,0.003523,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.843381,0.773013,0.840134,0.809971,0.817944,0.816889,0.025362,15
11,0.980800,0.067376,0.075513,0.034680,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.861051,0.781034,0.859445,0.824869,0.839669,0.833214,0.029316,6
12,0.113098,0.030703,0.010570,0.000604,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.838072,0.760405,0.843565,0.821108,0.828102,0.818250,0.029950,12
13,0.995674,0.073349,0.050113,0.003139,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.854074,0.775377,0.863517,0.829554,0.840920,0.832688,0.030886,8
14,0.109488,0.007874,0.012721,0.001912,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.842803,0.761710,0.836617,0.818981,0.826134,0.817249,0.028964,14
15,0.818593,0.026868,0.033296,0.004009,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857697,0.777367,0.859689,0.827556,0.843466,0.833155,0.030187,7

In [11]:
# Usrr inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [12]:
# Model predictions
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [2859.8212504]

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(