In [1]:
# Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
# Loading the dataset
dataset = pd.read_csv("insurance_pre.csv")
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
# Categorical data - One-Hot encodinng
dataset = pd.get_dummies(dataset,drop_first=True,dtype=int)
dataset.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
# Feature selection
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent.head()

   age     bmi  children  sex_male  smoker_yes
0   19  27.900         0         0           1
1   18  33.770         1         1           0
2   28  33.000         3         1           0
3   33  22.705         0         1           0
4   32  28.880         0         1           0

In [6]:
# Target or output
dependent = dataset[['charges']]
dependent.head()

       charges
0  16884.92400
1   1725.55230
2   4449.46200
3  21984.47061
4   3866.85520

In [10]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['linear','rbf'], 'C':[1,10,100],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(),param_grid,verbose=3,refit=True,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [1, 10, 100], 'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf']},
             verbose=3)

In [11]:
# Displaying the best model parameters
print("The best parameters are: ",grid.best_params_)
print("The best score is: ",grid.best_score_)

The best parameters are:  {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}
The best score is:  0.5352247456390156

In [12]:
# results of gridsearchcv
result = grid.cv_results_
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.129743,0.009526,0.017235,0.001533,1,auto,linear,"{'C': 1, 'gamma': 'auto', 'kernel': 'linear'}",-0.147592,-0.090685,-0.104805,-0.123874,-0.202393,-0.133870,0.039226,10
1,0.161736,0.010858,0.072666,0.005991,1,auto,rbf,"{'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}",-0.115171,-0.113204,-0.081329,-0.105826,-0.107122,-0.104530,0.012126,9
2,0.114179,0.007256,0.019438,0.002983,1,scale,linear,"{'C': 1, 'gamma': 'scale', 'kernel': 'linear'}",-0.147592,-0.090685,-0.104805,-0.123874,-0.202393,-0.133870,0.039226,10
3,0.151031,0.005960,0.088578,0.009759,1,scale,rbf,"{'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}",-0.115390,-0.110235,-0.079858,-0.104068,-0.108358,-0.103582,0.012406,8
4,0.161518,0.008986,0.019519,0.003469,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,3
5,0.202965,0.019561,0.086400,0.008970,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.113791,-0.110741,-0.079156,-0.103389,-0.106488,-0.102713,0.012303,7
6,0.149355,0.013725,0.017377,0.002145,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,3
7,0.141147,0.011180,0.074848,0.004678,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,6
8,0.349163,0.034448,0.017103,0.001276,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,1
9,0.158153,0.003904,0.074116,0.008006,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.100012,-0.098456,-0.072981,-0.096615,-0.102232,-0.094059,0.010699,5
10,0.341512,0.030046,0.017038,0.002112,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,1
11,0.143054,0.010771,0.073308,0.014115,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,12

In [13]:
# User inputs
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=float(input("Sex Male 0 or 1:"))
smoker_yes_input=float(input("Smoker yes 0 or 1:"))

In [14]:
# Model prediction
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print('Future_Prediction = ',Future_Prediction)

Future_Prediction =  [2033.53983628]

C:\Users\thiru\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(